# Generated by Django 5.2.6 on 2025-10-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizacao',
            name='data_visualizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='visualizacao',
            unique_together={('noticia', 'ip_usuario', 'data_visualizacao')},
        ),
        migrations.AddIndex(
            model_name='visualizacao',
            index=models.Index(fields=['data_visualizacao'], name='jcpemobile__data_vi_26e1a0_idx'),
        ),
    ]
