# Generated by Django 5.2.6 on 2025-10-20 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0002_visualizacao_data_visualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visualizacao',
            name='jcpemobile__data_vi_26e1a0_idx',
        ),
        migrations.RenameField(
            model_name='visualizacao',
            old_name='ip_usuario',
            new_name='ip_address',
        ),
        migrations.AlterUniqueTogether(
            name='visualizacao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='visualizacao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visualizacao',
            name='data_visualizacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 10, 20)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='visualizacao',
            unique_together={('noticia', 'ip_address', 'data')},
        ),
        migrations.AddIndex(
            model_name='visualizacao',
            index=models.Index(fields=['data'], name='jcpemobile__data_912d0d_idx'),
        ),
    ]
