# Generated by Django 5.2.6 on 2025-10-22 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0003_remove_visualizacao_jcpemobile__data_vi_26e1a0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticaSalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_salvamento', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvamentos', to='jcpemobile.noticia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_salvas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_salvamento'],
                'unique_together': {('usuario', 'noticia')},
            },
        ),
    ]
