# Generated by Django 5.2.6 on 2025-11-05 03:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0004_noticasalva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('pergunta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='jcpemobile.enquete')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_usuario', models.GenericIPAddressField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='jcpemobile.opcao')),
            ],
            options={
                'unique_together': {('opcao', 'ip_usuario')},
            },
        ),
    ]
