# Generated by Django 5.2.6 on 2025-11-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0005_enquete_opcao_voto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voto',
            unique_together=set(),
        ),
    ]
