# Generated by Django 5.2.6 on 2025-11-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0006_alter_voto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
