# Generated by Django 5.2.6 on 2025-11-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0007_alter_voto_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='noticia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquete', to='jcpemobile.noticia'),
        ),
    ]
