# Generated by Django 5.2.6 on 2025-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0009_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='categorias_preferidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_interessados', to='jcpemobile.categoria'),
        ),
    ]
