# Generated by Django 5.2.6 on 2025-11-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcpemobile', '0010_perfilusuario_categorias_preferidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='secao',
            field=models.CharField(choices=[('noticia_do_dia', 'Notícia do Dia'), ('social1', 'Social1'), ('jc360', 'JC360'), ('pernambuco', 'Pernambuco'), ('blog_do_torcedor', 'Blog do Torcedor'), ('ultimas_noticias', 'Últimas Notícias'), ('receita_da_boa', 'Receita da Boa')], default='noticia_do_dia', max_length=50, verbose_name='Seção'),
        ),
    ]
